add capo-v1alpha8-fix-* units

diff --git a/charts/sylva-units/values.yaml b/charts/sylva-units/values.yaml
--- a/charts/sylva-units/values.yaml
+++ b/charts/sylva-units/values.yaml
@@ -438,6 +438,16 @@ units:
             minAvailable: >-
               {{ .Values._internal.ha_cluster.is_ha | ternary 1 0 }}
 
+  kube-storage-version-migrator:
+    info:
+      description: installs kube-storage-version-migrator to assist apiVersion migrations
+    unit_templates:
+    - base-deps
+    repo: sylva-core
+    kustomization_spec:
+      path: ./kustomize-units/kube-storage-version-migrator
+      wait: true
+
   trivy-operator:
     info:
       description: installs Trivy operator
@@ -1711,6 +1721,195 @@ units:
       _components:
         - '{{ tuple "components/ha" (.Values._internal.ha_cluster.is_ha) | include "set-only-if" }}'
 
+  # this unit and the capo-v1alpha8-fix fix an issue we have with CAPO CRDs apiVersion
+  #
+  # in sylva 1.0.0 we used a custom build of intermediate version of CAPO, somewhere between 0.9.x and 0.10.x,
+  # to include an important fix, but we didn't realize that we would implicitely upgrade all CAPO resources to v1alpha8
+  # and because v1alpha8 is not present anymore in the final 0.10.x, we can't upgrade to 0.10.x
+  # without first fixing our CAPO resources to have them be stored into v1alpha7 (which exists in 0.9.x and 0.10.x)
+  #
+  # here is how this fix works:
+  # - we introduce the community kube-storage-version-migrator
+  # - we run a job that fixes the CRDs to indicate that the desired storage version is v1alpha7 (instead of v1alpha8)
+  #   note that this does not change any CAPO resource, only the CRD
+  # - (the capo unit won't reconcile in the background, because its got a dependsOn on capo-v1alpha8-fix)
+  # - we install a kube-storage-version-migrator resource to tell that tool to migrate all CAPO resources to v1alpha7
+  # - we run another job to remove v1lapha8 from the status.storedVersions of the CAPO CRDs
+  #   (this is necessary or else k8s will prevent us from installing the update of the CRD resource
+  #    from CAPO 0.12.3 that does not include v1alpha8 anymore)
+  # - the capo unit will then reconcile and install CAPO 0.10.x, including the new CRDs
+  #
+  # these units will be removed when not relevant anymore (e.g in the sylva release following the one in which they'll have been released)
+  capo-v1alpha8-fix-crd:
+    info:
+      description: handles CAPO apiVersion v1alpha8 issues (fix CRD)
+      details: fixes CAPO CRDs to use v1alpha7 as storage version
+      internal: true
+    unit_templates:
+    - base-deps
+    enabled_conditions:
+    - '{{ .Values._internal.capo_need_v1alpha8_fix }}'
+    repo: sylva-core
+    kustomization_spec:
+      path: ./kustomize-units/kube-job
+      wait: true
+      force: true
+      postBuild:
+        substitute:
+          JOB_NAME: v1alpha8-crd-fix
+          JOB_TARGET_NAMESPACE: '{{ .Release.Namespace }}'
+          JOB_CHECKSUM: '{{ .Values | toJson | sha256sum }}'
+      _patches:
+      - target:
+          kind: ClusterRole
+        patch: |
+          - op: replace
+            path: /rules
+            value:
+              - apiGroups: [apiextensions.k8s.io]
+                resources: [customresourcedefinitions]
+                verbs: [list, get, patch]
+      - target:
+          kind: ConfigMap
+        patch: |
+          - op: replace
+            path: /metadata/name
+            value: v1alpha8-crd-fix-{{ .Release.Namespace }}-cm
+          - op: replace
+            path: /data/kube-job.sh
+            value: |
+              #!/bin/bash
+              set -e
+
+              if ! (kubectl get crd kustomizations.kustomize.toolkit.fluxcd.io >/dev/null); then
+                echo "can't access CRDs, failing (service account issue)"
+                exit 1
+              fi
+
+              if ! (kubectl get crd openstackclusters.infrastructure.cluster.x-k8s.io >/dev/null); then
+                echo "CAPO not installed yet, this is a fresh install, nothing to do"
+                exit 0
+              fi
+
+              for kind in openstackmachines openstackmachinetemplates openstackclusters openstackclustertemplates; do
+                crd="$kind.infrastructure.cluster.x-k8s.io"
+                echo ------------- $crd -----------------
+
+                if (kubectl get crd $crd -o json | jq -e '.spec.versions[] | select(.name == "v1alpha8") | length == 0' &> /dev/null); then
+                  echo "no v1alpha8 in $crd, skipping"
+                  continue
+                fi
+
+                kubectl get crd $crd -o json | jq -e '.spec.versions | length == 4' || continue
+
+                echo "-- setting v1alpha7 as storage version for $crd"
+                kubectl patch crd $crd --type=json --patch='[{"op":"replace","path":"/spec/versions/3/storage","value":false},{"op":"replace","path":"/spec/versions/2/storage","value":true}]'
+
+                echo -n "-- ensuring that storage version for $crd has been set to v1alpha7: "
+                kubectl get crd $crd -o json | jq -e '.spec.versions[] | select(.storage) | .name == "v1alpha7"'
+
+              done
+
+  capo-v1alpha8-fix-resources:
+    info:
+      description: handles CAPO apiVersion v1alpha8 issues (fix resources)
+      details: migrates CAPO CRs from v1alpha8 back to v1alpha7
+      internal: true
+    enabled_conditions:
+    - '{{ .Values._internal.capo_need_v1alpha8_fix }}'
+    unit_templates:
+    - base-deps
+    depends_on:
+      capo-v1alpha8-fix-crd: true
+      kube-storage-version-migrator: true
+    repo: sylva-core
+    kustomization_spec:
+      path: ./kustomize-units/capo-v1alpha8-fix
+      wait: true
+
+  capo-v1alpha8-clear:
+    info:
+      description: handles CAPO apiVersion v1alpha8 issues (clear CRD)
+      details: fixes CAPO CRDs to clear v1alpha8 from stored versions
+      internal: true
+    unit_templates:
+    - base-deps
+    enabled_conditions:
+    - '{{ .Values._internal.capo_need_v1alpha8_fix }}'
+    depends_on:
+      capo-v1alpha8-fix-resources: true
+      kube-storage-version-migrator: true
+    repo: sylva-core
+    kustomization_spec:
+      path: ./kustomize-units/kube-job
+      wait: true
+      force: true
+      postBuild:
+        substitute:
+          JOB_NAME: v1alpha8-clear
+          JOB_TARGET_NAMESPACE: '{{ .Release.Namespace }}'
+          JOB_CHECKSUM: '{{ .Values | toJson | sha256sum }}'
+      _patches:
+      - target:
+          kind: ClusterRole
+        patch: |
+          - op: replace
+            path: /rules
+            value:
+              - apiGroups: [apiextensions.k8s.io]
+                resources: [customresourcedefinitions, customresourcedefinitions/status]
+                verbs: [list, get, patch]
+              - apiGroups: [migration.k8s.io]
+                resources: [storageversionmigrations]
+                verbs: [list, get, watch]
+      - target:
+          kind: ConfigMap
+        patch: |
+          - op: replace
+            path: /metadata/name
+            value: v1alpha8-clear-{{ .Release.Namespace }}-cm
+          - op: replace
+            path: /data/kube-job.sh
+            value: |
+              #!/bin/bash
+              set -e
+
+              if ! (kubectl get crd kustomizations.kustomize.toolkit.fluxcd.io >/dev/null); then
+                echo "can't access CRDs, failing (service account issue)"
+                exit 1
+              fi
+
+              if ! (kubectl get crd openstackclusters.infrastructure.cluster.x-k8s.io >/dev/null); then
+                echo "CAPO not installed yet, this is a fresh install, nothing to do"
+                exit 0
+              fi
+
+              # we explicitly wait for the migration to be done, because since StorageVersionMigration isn't kstatus-compliant
+              # the readiness of the capo-v1alpha8-fix-resources unit isn't sufficient to guarantee that all resources
+              # were migrated
+              #
+              for kind in openstackmachines openstackmachinetemplates openstackclusters openstackclustertemplates; do
+                crd="$kind.infrastructure.cluster.x-k8s.io"
+                echo ------------- $crd, wait for all resources to have been migrated -----------------
+
+                echo "wait for all resources to have been migrated..."
+                kubectl wait StorageVersionMigration capo-v1alpha8-fix-$kind --timeout 60s \
+                  --for='jsonpath={.status.conditions[?(@.type=="Succeeded")].status}=True'
+              done
+
+              for kind in openstackmachines openstackmachinetemplates openstackclusters openstackclustertemplates; do
+                crd="$kind.infrastructure.cluster.x-k8s.io"
+                echo ------------- $crd, cleaning storedVersions -----------------
+
+                if (kubectl get crd $crd -o json | jq -e '.spec.versions[] | select(.name == "v1alpha8") | length == 0' &> /dev/null); then
+                  echo "no v1alpha8 in $crd, skipping"
+                  continue
+                fi
+
+                echo "cleaning v1alpha8 from .status.storedVersions"
+                kubectl patch crd $crd --type=json --patch='[{"op":"replace","path":"/status/storedVersions","value":["v1alpha7"]}]' --subresource=status
+              done
+
   capo:
     info:
       description: installs OpenStack CAPI infra provider
@@ -1719,6 +1918,7 @@ units:
     unit_templates:
     - base-deps
     depends_on:
+      capo-v1alpha8-clear: '{{ .Values._internal.capo_need_v1alpha8_fix }}'
       cert-manager: true
     kustomization_spec:
       path: ./kustomize-units/capo
@@ -5790,8 +5990,15 @@ _internal:
   default_os_images_info_configmap: os-images-info-{{ tuple . .Values._internal.os_images_info_input_hash | include "interpret-as-string" }}
   os_images_info_configmap: '{{ .Values._internal.default_os_images_info_configmap }}'  # overridden in workload-cluster.values.yaml
 
+
   default_calico_autodetection_method:
     canReach: '{{ not (empty .Values.cluster.mgmt_cluster_ip) | ternary .Values.cluster.mgmt_cluster_ip .Values.cluster.cluster_virtual_ip }}'
+
+  capo_need_v1alpha8_fix: >-
+    {{
+    .Capabilities.APIVersions | has "infrastructure.cluster.x-k8s.io/v1alpha8/OpenStackCluster" | include "preserve-type"
+    }}
+
 
 shared_workload_clusters_values:
   ntp: '{{ .Values.ntp | include "set-if-defined" }}'
