tert

diff --git a/charts/sylva-units/values.yaml b/charts/sylva-units/values.yaml
--- a/charts/sylva-units/values.yaml
+++ b/charts/sylva-units/values.yaml
@@ -7742,10 +7742,27 @@ cluster:
   additional_commands:
     pre_bootstrap_commands:
     - | 
-      . /etc/os-release || exit 1
-      [[ $ID == ubuntu ]] && p=/usr/local/share/ca-certificates/ca.crt
-      [[ $ID == opensuse || $ID == sles ]] && p=/etc/pki/trust/anchors/ca.crt
-      echo {{ .Values.os_extra_ca_certs }} | sudo tee $p >/dev/null && sudo update-ca-certificates
+      if [ -f /etc/os-release ]; then
+          . /etc/os-release
+      else
+          echo "Cannot detect OS. /etc/os-release not found."
+          exit 1
+      fi
+      case "$ID" in
+          ubuntu)
+              CERT_PATH="/usr/local/share/ca-certificates/ca.crt"
+              ;;
+          opensuse* | sles)
+              CERT_PATH="/etc/pki/trust/anchors/ca.crt"
+              ;;
+          *)
+              echo "Unsupported OS: $ID"
+              exit 1
+              ;;
+      esac
+      echo "Creating certificate at: $CERT_PATH"
+      printf "{{ .Values.os_extra_ca_certs }}" | sudo tee "$CERT_PATH" > /dev/null
+      echo "Done."
 
   # can be set to true to do an RKE2 deployment disconnected from the Internet:
   air_gapped: false
