add tools/generate-renovate-json.sh

diff --git a/.gitlab/ci/main-pipeline-checks.yml b/.gitlab/ci/main-pipeline-checks.yml
--- a/.gitlab/ci/main-pipeline-checks.yml
+++ b/.gitlab/ci/main-pipeline-checks.yml
@@ -266,6 +266,23 @@ check-sylva-unit-dependencies:
           exit 1
       fi
 
+check-renovate-json:
+  extends: [.lint-base]
+  script:
+    - set -e
+    - tools/generate-renovate-json.sh
+    - |
+      if [[ -n $(git status renovate.json -s --porcelain) ]]; then
+          echo -e "\033[0;31m[ERROR] renovate.json was regenerated with 'tools/generate-renovate-json.sh'\033[0m"
+          echo
+          git diff renovate.json
+          echo
+          echo "Git status:"
+          echo
+          git status renovate.json -s --porcelain
+          exit 1
+      fi
+
 ###########################
 # Gitleaks customization
 ###########################
