Handle API pagination to retrieve artifacts

diff --git a/.gitlab/ci/templates-deployments.yml b/.gitlab/ci/templates-deployments.yml
--- a/.gitlab/ci/templates-deployments.yml
+++ b/.gitlab/ci/templates-deployments.yml
@@ -102,10 +102,28 @@ include:
     function download_artifact() {
     export job_name=$1
     artifact_name=$2
+    page=1
+    job_id=""
     if [[ $CI_JOB_NAME != $job_name ]]; then
-      JOB_ID=$(curl --location -f --header "${ARTIFACT_AUTHENTICATION_HEADER:-JOB-TOKEN: $CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/jobs" | yq '.[] | select(.name == env(job_name)) | .id')
-      echo -e "Retrieving \\e[1;94m$artifact_name\\e[0m artifact from \\e[1;92m$job_name\\e[0m job"
-      curl --location -f -o $artifact_name --header "${ARTIFACT_AUTHENTICATION_HEADER:-JOB-TOKEN: $CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/jobs/$JOB_ID/artifacts/$artifact_name"
+      while [[ -z "$job_id" ]]; do
+        job_id=$(curl --silent -S --location -f --header "${ARTIFACT_AUTHENTICATION_HEADER:-JOB-TOKEN: $CI_JOB_TOKEN}" \
+          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/jobs?page=${page}" | yq '.[] | select(.name == env(job_name)) | .id')
+
+        if [[ -n "${job_id}" ]]; then
+          echo -e "Retrieving \\e[1;94m$artifact_name\\e[0m artifact from \\e[1;92m$job_name with ID: ${job_id}\\e[0m job"
+          curl --location --silent -S -f -o $artifact_name --header "${ARTIFACT_AUTHENTICATION_HEADER:-JOB-TOKEN: $CI_JOB_TOKEN}" \
+          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/jobs/${job_id}/artifacts/$artifact_name"
+          break
+        fi
+        next_page=$(curl --silent -S --head --location -f --header "${ARTIFACT_AUTHENTICATION_HEADER:-JOB-TOKEN: $CI_JOB_TOKEN}" \
+          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/jobs?page=${page}" \
+          | grep -Fi X-Next-Page | awk '{print $2}' | tr -d '\r')
+        if [[ -z "$next_page" ]]; then
+          echo "No more pages to check. Job not found."
+          exit 1
+        fi
+        page=$next_page
+      done
     fi
     }
 
